FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl/star.samana.cloud.2024.crt /etc/nginx/ssl/star.samana.cloud.2024.crt
COPY ssl/star.samana.cloud.2024.pem /etc/nginx/ssl/star.samana.cloud.2024.pem